### ISSUE TITLE
Support game launching without entering the .elf file directory

### ISSUE THREAD

**Issue by leonstyhre** [lindbergh-loader/lindbergh-loader#73]
Hi!

I'm currently investigating possible support for Lindbergh Loader in ES-DE (https://es-de.org) and I'm nearly at a workable solution.
However there is one small hurdle left that would require a change in the emulator.

At the moment you need to enter the directory of the .elf file and run the game from there, for example:

```
cd /home/user/ROMs/arcade/2spicy.lindbergh/disk0/elf
/var/lib/flatpak/exports/bin/com.github.lindberghloader apacheM.elf
```

If you could implement support for this approach, then it would work with ES-DE:
```
cd /home/user/ROMs/arcade/2spicy.lindbergh
/var/lib/flatpak/exports/bin/com.github.lindberghloader disk0/elf/apacheM.elf
```

Attempting to run this however gives the following error message:
`ERROR: ld.so: object '/app/lib32/lindbergh.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.`

If you are familiar with ES-DE the following configuration entry could be used if you make this change:
```xml
<command label="Lindbergh Loader (Standalone)">%STARTDIR%=%GAMEENTRYDIR% %EMULATOR_LINDBERGH-LOADER% %INJECT%=%BASENAME%/%BASENAME%.commands</command>
```

And you'd simply need a file named `/home/user/ROMs/arcade/2spicy.lindbergh/2spicy.lindbergh.commands` that contains the following string (i.e. the users would add this file themselves):
```
disk0/elf/apacheM.elf
```

This file content is then injected on game launch so the correct parameters are passed to the emulator. This would lead to a very clean and flexible configuration.

To clarify further, this is the log output from ES-DE:
```
Mar 20 20:58:24 Info:   Launching game "2spicy" from system "Arcade (arcade)"...
Mar 20 20:58:24 Debug:  FileData::launchGame(): Using alternative emulator "Lindbergh Loader (Standalone)" as configured for system "arcade"
Mar 20 20:58:24 Debug:  FileData::findEmulator(): Emulator found via staticpath rule
Mar 20 20:58:24 Debug:  FileData::launchGame(): Emulator set to "/var/lib/flatpak/exports/bin/com.github.lindberghloader"
Mar 20 20:58:24 Debug:  FileData::launchGame(): Setting start directory to "/home/user/ROMs/arcade/2spicy.lindbergh"
Mar 20 20:58:24 Debug:  FileData::launchGame(): Injecting from file "/home/user/ROMs/arcade/2spicy.lindbergh/2spicy.lindbergh.commands"
Mar 20 20:58:24 Debug:  Raw emulator launch command:
Mar 20 20:58:24 Debug:  %STARTDIR%=%GAMEENTRYDIR% %EMULATOR_LINDBERGH-LOADER% %INJECT%=%BASENAME%/%BASENAME%.commands
Mar 20 20:58:24 Info:   Expanded emulator launch command:
Mar 20 20:58:24 Info:   /var/lib/flatpak/exports/bin/com.github.lindberghloader disk0/elf/apacheM.elf
Mar 20 20:58:24 Debug:  Platform::launchGameUnix():
Mar 20 20:58:24 Debug:  Output from launched game:
ERROR: ld.so: object '/app/lib32/lindbergh.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
```

Many thanks in advance!

**Comment by udance4ever** [comment]
I would love to see this working in ES.  This is related to #72 as Batocera Linux currently has to change into the directory (as you've noticed), copy executable and shared libraries and generate a config file in that directory to launch titles.

the way we currently handle locating the executable directory is where a `2spicy.game` is put.  Your proposed solution eliminates having to locate this file.

**Comment by dkeruza-neo** [comment]
Last commit add the possibility to launch games from a different folder. Also, the executable will look for the file lindbergh.so in the game's folder or in your linux distro lib folder (where 32 bit libraries are) for example`/usr/lib/i386-linux-gnu`.

Try it and report back please.

**Comment by SeongGino** [comment]
Not OP, but did just try it. It only seems to work with paths that only has alphanumerics and no spaces.

Original title `The House of the Dead 4 (Rev C)`, which contains spaces and paranthesis:
```bash
$ flatpak run com.github.lindberghloader -g "/mnt/Firebomb/ArcadeGames/Lindbergh/The House of the Dead 4 (Rev C)/elf"
[0000.000] ERROR> Could not calculate the Elf CRC32.
[0000.000] INFO> Starting $ /mnt/Firebomb/ArcadeGames/Lindbergh/The House of the Dead 4 (Rev C)/elf/hod4M.elf
ERROR: ld.so: object '/app/lib32/lindbergh.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
sh: -c: line 1: syntax error near unexpected token `('
sh: -c: line 1: `/mnt/Firebomb/ArcadeGames/Lindbergh/The House of the Dead 4 (Rev C)/elf/hod4M.elf'
```

Remove paranthesis (`The House of the Dead 4 Rev C`):
```bash
$ flatpak run com.github.lindberghloader -g "/mnt/Firebomb/ArcadeGames/Lindbergh/The House of the Dead 4 Rev C/elf"
[0000.000] ERROR> Could not calculate the Elf CRC32.
[0000.000] INFO> Starting $ /mnt/Firebomb/ArcadeGames/Lindbergh/The House of the Dead 4 Rev C/elf/hod4M.elf
ERROR: ld.so: object '/app/lib32/lindbergh.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
sh: line 1: /mnt/Firebomb/ArcadeGames/Lindbergh/The: No such file or directory
```

Changed to just `hod4`
```bash
$ flatpak run com.github.lindberghloader -g "/mnt/Firebomb/ArcadeGames/Lindbergh/hod4/elf"
[0000.000] INFO> Starting $ /mnt/Firebomb/ArcadeGames/Lindbergh/hod4/elf/hod4M.elf
ERROR: ld.so: object '/app/lib32/lindbergh.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
[0000.000] WARN> Seems like you're not in debian-like system. There might be unexpected issues.

SEGA Lindbergh Emulator
By the Lindbergh Development Team 2025

  GAME:        The House of the Dead 4 Rev C
  GAME ID:     SBLC
  DVP:         DVP-0003C
  GPU VENDOR:  NVIDIA Corporation

  SDL RESOLUTION: 2560x1440
...
```

**Comment by dkeruza-neo** [comment]
It should be good now. I added a check to see if the path contains spaces.
Please report back. Thanks

**Comment by leonstyhre** [comment]
Hi, I've tried build v191 and unfortunately it still behaves the same as before:

```
cd ~/ROMs/arcade/lindbergh/2spicy.lindbergh
/var/lib/flatpak/exports/bin/com.github.lindberghloader disk0/elf/apacheM.elf
Warning: The ELF you are running is not Clean and might cause unwanted behavior.
         Make sure you ELF and game dump are clean before reporting issues.
         If you are sure the ELF is clean, please report it to us.
[0000.000] INFO> Starting $ ./disk0/elf/apacheM.elf
ERROR: ld.so: object '/app/lib32/lindbergh.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
[0000.000] WARN> Cannot open lindbergh.conf, using default values.
[0000.000] WARN> Seems like you're not in debian-like system. There might be unexpected issues.
Error opening nnstdshader.vert.
```

The above commands is equivalent to what ES-DE is doing when attempting to launch the game.

Doing a cd into disk0/elf and running the apacheM.elf file from there is working correctly.

I'm on Kubuntu 24.04 LTS so also not sure why it states it's not a Debian-like system?

Thanks!

**Comment by SeongGino** [comment]
At least on my setup, current master/v191 does seem to work passing the path along now. So not sure what OP's issue is - AMD related, perhaps?

**Comment by SeongGino** [comment]
Though abs paths works fine here with the flatpak, I did notice that the elf seems to append itself after quotations.
```bash
$ flatpak run com.github.lindberghloader -g "/mnt/Firebomb/ArcadeGames/Lindbergh/Lets Go Jungle"
[0000.000] INFO> Starting $ "/mnt/Firebomb/ArcadeGames/Lindbergh/Lets Go Jungle"/lgj_final
```

**Comment by leonstyhre** [comment]
@SeongGino But you are using the -g flag, this works quite differently compared to running individual game files. On the other hand I'm not very familiar with the Lindbergh system, perhaps the users would never ever need to specify a precise game file to run, i.e. passing the directory could be enough? But it really needs to be the case for 100% of the games or otherwise it's not a usable option/solution.

**Comment by leonstyhre** [comment]
Unfortunately that syntax is problematic for a frontend such as ES-DE. There is a command configuration that is setup like the following:

`<command label="Lindbergh Loader (Standalone)">%STARTDIR%=%GAMEENTRYDIR% %EMULATOR_LINDBERGH-LOADER% %INJECT%=%BASENAME%/%BASENAME%.commands</command>`

The .commands file contains the path to the .elf file to execute, like the following:
`disk0/elf/apacheM.elf`

What you propose requires that the .elf file is injected before the -g flag which makes it impossible to make this work cleanly with a frontend like ES-DE as two separate files would need to be injected at separate locations in the command string. The good solution would really be to pass the relative path to the .elf file as described in my first message when I created this issue, i.e. equivalent to this command:

`/var/lib/flatpak/exports/bin/com.github.lindberghloader disk0/elf/apacheM.elf`

This is in my opinion a logical way to launch a game file by simply passing the relative path to the .elf file, and this makes it possible to setup a clean and logical configuration in a frontend such as ES-DE.

Would it be possible to add support for this? The only difference from what's been possible in the past is the need to not having to cd into the disk0/elf directory which is also problematic to configure for a frontend such as ES-DE. If not doing cd to the directory the following error message is displayed: 
`ERROR: ld.so: object '/app/lib32/lindbergh.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.`

Anyway, if this change is made to Lindbergh Loader, then someone who really wants to pass the -g flag instead can do it by simply adding the following to the .commands file:
`-g disk0/elf`

This leads to a clean setup while still offering flexibility for someone that would still prefer to use the -g flag for some reason (I don't see any reason to use this personally but I'm also not that familiar with the Lindbergh system so perhaps I'm missing something here).

**Comment by dkeruza-neo** [comment]
That is not the way the loader was intended to work. 
What I could do is add a separate option just for the front-end. 
for example `./lindbergh --esde disk0/elf/apacheM.elf`

> ERROR: ld.so: object '/app/lib32/lindbergh.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

That is not an actual error, ignore those.

**Comment by leonstyhre** [comment]
Thanks, that would be great!

But please don't name it --esde as I'm pretty sure other frontends will also want to use that option, perhaps call it -f or --file or --direct or something along those lines?

Thanks :)

**Comment by dkeruza-neo** [comment]
Should be good now, read the instructions inside docs/guide.md

Let me know if it works fine.

**Comment by leonstyhre** [comment]
Hi, I just tried it with v199 and unfortunately it still doesn't work:

```
cd ~/ROMs/arcade/lindbergh/2spicy.lindbergh
/var/lib/flatpak/exports/bin/com.github.lindberghloader disk0/elf/apacheM.elf
bwrap: Can't mkdir /app/lib/i386-linux-gnu: Read-only file system
error: ldconfig failed, exit status 256
```

**Comment by dkeruza-neo** [comment]
> Hi, I just tried it with v199 and unfortunately it still doesn't work:
> 
> ```
> cd ~/ROMs/arcade/lindbergh/2spicy.lindbergh
> /var/lib/flatpak/exports/bin/com.github.lindberghloader disk0/elf/apacheM.elf
> bwrap: Can't mkdir /app/lib/i386-linux-gnu: Read-only file system
> error: ldconfig failed, exit status 256
> ```

I pushed the fix, it is building now. There was a bug in the Flatpak script.

**Comment by leonstyhre** [comment]
Hi, it still doesn't work in v203 unfortunately but now it's a new error message:

```
cd ~/ROMs/arcade/lindbergh/2spicy.lindbergh
/var/lib/flatpak/exports/bin/com.github.lindberghloader disk0/elf/apacheM.elf
Warning: The ELF you are running is not Clean and might cause unwanted behavior.
         Make sure you ELF and game dump are clean before reporting issues.
         If you are sure the ELF is clean, please report it to us.
[0000.000] INFO> Starting $ "disk0/elf/"apacheM.elf
ERROR: ld.so: object '/app/lib32/lindbergh.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
sh: line 1: disk0/elf/apacheM.elf: No such file or directory
```

The file does exist though:
```
du -sh disk0/elf/apacheM.elf
6,3M    disk0/elf/apacheM.elf
```

**Comment by dkeruza-neo** [comment]
It works fine now.
You have to add permissions to the folder containing the games. 
I suggest using flatseal.
Read the guide in the docs folder.

**Comment by leonstyhre** [comment]
But I've already given "All system files" permissions to Lindbergh Loader via Flatseal, do I need to give some additional permissions for it to work correctly?

**Comment by leonstyhre** [comment]
I tried disabling the "All system files" permission in Flatseal, and then I get another error message, which I guess makes sense as the directory is not accessible by the Flatpak:

```
/var/lib/flatpak/exports/bin/com.github.lindberghloader disk0/elf/apacheM.elf
[0000.000] ERROR> disk0/elf is not a valid directory here.
```

So file permissions is not the problem at least.

**Comment by dkeruza-neo** [comment]
First, you have to pass the full path I believe but I'm not sure as I never tried with a partial path.
If it still does not see the elf, means you don't have the right  permissions to the folder.

**Comment by SeongGino** [comment]
I tried this myself with `v203` and it's definitely working (even in spite of the warning).
```bash
$ flatpak run com.github.lindberghloader "/mnt/Firebomb/ArcadeGames/Lindbergh/The House of the Dead EX/elf/hodexRI.elf"
[0000.000] WARN> The current path contains spaces, this most likely will cause issues.
[0000.000] WARN> Please, make sure you don't use spaces in the path.
Warning: The ELF you are running is not Clean and might cause unwanted behavior.
         Make sure you ELF and game dump are clean before reporting issues.
         If you are sure the ELF is clean, please report it to us.
[0000.386] INFO> Starting $ "/mnt/Firebomb/ArcadeGames/Lindbergh/The House of the Dead EX/elf/"hodexRI.elf
ERROR: ld.so: object 'lindbergh.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
[0000.000] WARN> Seems like you're not in debian-like system. There might be unexpected issues.

SEGA Lindbergh Emulator
By the Lindbergh Development Team 2025

  GAME:        Ai Sareruyori Ai Shitai: The House of the Dead EX
  GAME ID:     SBRC
  DVP:         DVP-0063
  GPU VENDOR:  NVIDIA Corporation

  SDL RESOLUTION: 2560x1440

MyApp::Initialize()
...
```

```bash
$ flatpak run com.github.lindberghloader -g "/mnt/Firebomb/ArcadeGames/Lindbergh/The House of the Dead EX/elf"
Warning: The ELF you are running is not Clean and might cause unwanted behavior.
         Make sure you ELF and game dump are clean before reporting issues.
         If you are sure the ELF is clean, please report it to us.
[0000.000] INFO> Starting $ "/mnt/Firebomb/ArcadeGames/Lindbergh/The House of the Dead EX/elf/"hodexRI.elf
ERROR: ld.so: object '/app/lib32/lindbergh.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
[0000.000] WARN> Seems like you're not in debian-like system. There might be unexpected issues.

SEGA Lindbergh Emulator
By the Lindbergh Development Team 2025

  GAME:        Ai Sareruyori Ai Shitai: The House of the Dead EX
  GAME ID:     SBRC
  DVP:         DVP-0063
  GPU VENDOR:  NVIDIA Corporation

  SDL RESOLUTION: 2560x1440

MyApp::Initialize()
...
```

**Comment by leonstyhre** [comment]
I can confirm that passing the absolute path works, i.e. this successfully launches the game in v203:

 ```
/var/lib/flatpak/exports/bin/com.github.lindberghloader $(pwd)/disk0/elf/apacheM.elf
```

But this is quite messy to pass from ES-DE and I'm not sure that it will work under all circumstances such as when using the so-called "directories interpreted as files" functionality in ES-DE.

Is it not possible to update Lindberg Loader to be able to pass a relative path, i.e. like this?

```
cd ~/ROMs/arcade/lindbergh/2spicy.lindbergh
/var/lib/flatpak/exports/bin/com.github.lindberghloader disk0/elf/apacheM.elf
```

**Comment by leonstyhre** [comment]
@SeongGino Yes but passing the absolute path to the .elf file is problematic, being able to pass the relative path as originally requested in this issue would really simplify the configuration from the frontend, and it's also logical in my opion.

**Comment by dkeruza-neo** [comment]
As suggested, it is not a good practice to use spaces in folders.
Then, idk how ES-DE works, but why would it not support full paths?
If it doesn't, it would be a limitation on their part.

**Comment by dkeruza-neo** [comment]
As suggested, it is not a good practice to use spaces in folders.
Then, idk how ES-DE works, but why would it not support full paths?
If it doesn't, it would be a limitation on their part.

Try passing a relative path like this:
./disk0/elf/apacheM.elf

**Comment by dkeruza-neo** [comment]
The loader changes to the directory where the game is located to run it.

That is how the games are designed to run. They use mostly relative paths to locate the game  files.

**Comment by leonstyhre** [comment]
Unfortunately adding ./ doesn't work:

```
cd ~/ROMs/arcade/lindbergh/2spicy.lindbergh
/var/lib/flatpak/exports/bin/com.github.lindberghloader ./disk0/elf/apacheM.elf
Warning: The ELF you are running is not Clean and might cause unwanted behavior.
         Make sure you ELF and game dump are clean before reporting issues.
         If you are sure the ELF is clean, please report it to us.
[0000.000] INFO> Starting $ "./disk0/elf/"apacheM.elf
ERROR: ld.so: object '/app/lib32/lindbergh.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
sh: line 1: ./disk0/elf/apacheM.elf: No such file or directory
```

ES-DE for sure supports passing the full path, but there are many special situations where users do weird things like putting spaces in directory names and whatnot, and without relative path support in Lindbergh Loader as requested in this issue I'm not sure that I can add a configuration for this emulator that works reliably under all circumstances.

I can still add support and caveat in the documentation that it has to be super specific or otherwise it simply won't work, but having the relative path support would make it more reliable and simpler for the end user.

**Comment by dkeruza-neo** [comment]
I'll look into it to see if it is possible.
I know what happened there.
The loader cd to the folder "disk0/elf/" and then, tried to load the elf using the whole path "./disk0/elf/apacheM.elf" and of course wasn't able to find it as it is already in that location.

I am wondering how I can detect if the path passed is full or relatively.

**Comment by leonstyhre** [comment]
You could do an ugly hack I guess and check whether the path starts with a / character, as absolute paths always does that. If not then it's for sure not an absolute path.

It would be so much better if you can make this work, so I hope it's doable :)

**Comment by dkeruza-neo** [comment]
Yeahh, that is what I thought.
I can also concatenate the current dir with the relative path and make sure it exists.

I'll find a way.

**Comment by leonstyhre** [comment]
Sounds like a plan!

Just let me know when it's ready for testing, I'm looking forward to adding support for your emulator to the next ES-DE release!

**Comment by dkeruza-neo** [comment]
@leonstyhre I see you have an appimage in ES-DE. 
Would you help me with building one?
The big issue I have is that I need to build the X11 libs, Mesa and a few more to make the loader work in for example Arch.
Also, why you don't have a flatpak?

**Comment by leonstyhre** [comment]
Sure! And you could also join the ES-DE Discord server where I'm online every day:
https://discord.gg/42jqqNcHf9

**Comment by dkeruza-neo** [comment]
I joined the channel and PMd you.

**Comment by dkeruza-neo** [comment]
Implemented.

**Comment by leonstyhre** [comment]
Thanks for implementing this!

**Comment by albmm74** [comment]
I used to run Lindbegh games on ES-DE adding an .elf extension to the ELF files, cause that was the only way for game window clossing and return to frontend (pressing Alt+T), and that worked perfect; now I'm runing .sh launchers for every game (removing the .elf extension), cause with latest appimage builds I can close games with Alt+F4, as any other emulator.
